### ISSUE TITLE
Passing odd number of arguments for logging caused program panic and exit

### ISSUE THREAD

**Issue by leopoldxx** [crossplane/oam-kubernetes-runtime#143]
**Describe the bug**

Passing odd number of arguments for logging caused program panic and exit.

```
2020-07-26T18:52:02.532+0800	INFO	ManualScalarTrait	Get the manualscalar trait	{"ReplicaCount": 3, "Annotations": {"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"core.oam.dev/v1alpha2\",\"kind\":\"ApplicationConfiguration\",\"metadata\":{\"annotations\":{},\"name\":\"example-appconfig\",\"namespace\":\"default\"},\"spec\":{\"components\":[{\"componentName\":\"example-component\",\"parameterValues\":[{\"name\":\"instance-name\",\"value\":\"example-appconfig-workload\"},{\"name\":\"image\",\"value\":\"wordpress:php7.2\"}],\"scopes\":[{\"scopeRef\":{\"apiVersion\":\"core.oam.dev/v1alpha2\",\"kind\":\"HealthScope\",\"name\":\"example-health-scope\"}}],\"traits\":[{\"trait\":{\"apiVersion\":\"core.oam.dev/v1alpha2\",\"kind\":\"ManualScalerTrait\",\"metadata\":{\"name\":\"example-appconfig-trait\"},\"spec\":{\"replicaCount\":3}}}]}]}}\n"}}
2020-07-26T18:52:02.532+0800	DPANIC	ManualScalarTrait	odd number of arguments passed as key-value pairs for logging	{"manualscalar trait": "default/example-appconfig-trait", "ignored key": "example-appconfig-trait"}
github.com/go-logr/zapr.handleFields
	/root/workspace/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:106
github.com/go-logr/zapr.(*zapLogger).Error
	/root/workspace/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:129
github.com/crossplane/oam-kubernetes-runtime/pkg/controller/v1alpha2/core/traits/manualscalertrait.(*Reconciler).Reconcile
	/root/workspace/go/src/github.com/crossplane/oam-kubernetes-runtime/pkg/controller/v1alpha2/core/traits/manualscalertrait/manualscalertrait_controller.go:98
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/root/workspace/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:256
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/root/workspace/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/root/workspace/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/root/workspace/go/pkg/mod/k8s.io/apimachinery@v0.18.5/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/root/workspace/go/pkg/mod/k8s.io/apimachinery@v0.18.5/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/root/workspace/go/pkg/mod/k8s.io/apimachinery@v0.18.5/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
	/root/workspace/go/pkg/mod/k8s.io/apimachinery@v0.18.5/pkg/util/wait/wait.go:90
E0726 18:52:02.532202   23438 runtime.go:76] Observed a panic: odd number of arguments passed as key-value pairs for logging
goroutine 270 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x14113a0, 0xc0013a09c0)
	/root/workspace/go/pkg/mod/k8s.io/apimachinery@v0.18.5/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/root/workspace/go/pkg/mod/k8s.io/apimachinery@v0.18.5/pkg/util/runtime/runtime.go:48 +0x82
panic(0x14113a0, 0xc0013a09c0)
	/root/workspace/go/download/go/src/runtime/panic.go:679 +0x1b2
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0006bcb00, 0xc00134e7c0, 0x1, 0x1)
	/root/workspace/go/pkg/mod/go.uber.org/zap@v1.10.0/zapcore/entry.go:229 +0x546
go.uber.org/zap.(*Logger).DPanic(0xc00142e600, 0x167ce3e, 0x3d, 0xc00134e7c0, 0x1, 0x1)
	/root/workspace/go/pkg/mod/go.uber.org/zap@v1.10.0/logger.go:215 +0x7f
github.com/go-logr/zapr.handleFields(0xc00142e600, 0xc0013a0980, 0x1, 0x1, 0xc00134e740, 0x1, 0x1, 0x0, 0x0, 0x0)
	/root/workspace/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:106 +0x5ce
github.com/go-logr/zapr.(*zapLogger).Error(0xc001a12840, 0x18178a0, 0xc000e3cc80, 0x1637f6c, 0xc, 0xc0013a0980, 0x1, 0x1)
	/root/workspace/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:129 +0x23e
github.com/crossplane/oam-kubernetes-runtime/pkg/controller/v1alpha2/core/traits/manualscalertrait.(*Reconciler).Reconcile(0xc000523500, 0xc000046d29, 0x7, 0xc0006b5100, 0x17, 0xc001f5dcb0, 0xc00067e3f0, 0xc000770128, 0x18265c0)
	/root/workspace/go/src/github.com/crossplane/oam-kubernetes-runtime/pkg/controller/v1alpha2/core/traits/manualscalertrait/manualscalertrait_controller.go:98 +0x12ce
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0006ce6c0, 0x14d3dc0, 0xc000438020, 0x0)
	/root/workspace/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:256 +0x162
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0006ce6c0, 0x0)
	/root/workspace/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:232 +0xcb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc0006ce6c0)
	/root/workspace/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000767620)
	/root/workspace/go/pkg/mod/k8s.io/apimachinery@v0.18.5/pkg/util/wait/wait.go:155 +0x5e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000767620, 0x1817ac0, 0xc00076f4a0, 0x1, 0xc000538ea0)
	/root/workspace/go/pkg/mod/k8s.io/apimachinery@v0.18.5/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000767620, 0x3b9aca00, 0x0, 0x1, 0xc000538ea0)
	/root/workspace/go/pkg/mod/k8s.io/apimachinery@v0.18.5/pkg/util/wait/wait.go:133 +0xaa
k8s.io/apimachinery/pkg/util/wait.Until(0xc000767620, 0x3b9aca00, 0xc000538ea0)
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Cluster information**

**Additional context**

**Comment by leopoldxx** [comment]
I create a pr to fix the log itself. Bug if should we add a recover routine when enter `Reconcile` logic ?
